In [ ]:
##...yamoah min-edit-distance....##

In [2]:
import numpy as np

In [ ]:
def main(source, target):
    distMatrix = min_edit_distance(source, target)
    #distMatrix = initiate(distMatrix, len(source), len(target))
    #print(distMatrix)
    med = recurrRelation(distMatrix)

In [ ]:
def min_edit_distance(source, target):
    n = len(source)
    m = len(target)
    print(source +" "+ str(n))
    print(target +" "+ str(m))
    myMatrix = np.zeros((n+1,m+1))
    return myMatrix

In [ ]:
def initiate(distanceMatrix, n, m):
    #print(distanceMatrix)
    #distanceMatrix.shape
    for i in range(1,n)
        distanceMatrix[i,0] = distanceMatrix[i-1,0] + 1 #(source[i])
    for i in range(1,m)
        distanceMatrix[0,j] = distanceMatrix[0,j-1] + 1 #(target[j])
    return distanceMatrix

In [ ]:
def recurrRelation(D):
    for i in range(1,n)
        for i in range(1,m)
            D[i,j]=min((D[i-1,j]+1),(D[i-1,j-1]+1),(D[i,j-1]+1))
    return D[n,m]

In [ ]:
#main("good", "b")

In [16]:
#b = np.zeros((3,4))
#b.shape
#print(b)
#print("----------------")
#for i in range(1,3):
#    b[0,i] = i+10
#print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
----------------
[[10. 11. 12.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
